vich_uploader:
  db_driver: orm

  mappings:
    media:
      uri_prefix: "%media_attachments%"
      upload_destination: "%kernel.project_dir%/public%media_attachments%"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      delete_on_update: false
      delete_on_remove: false
