controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

preambule:
  path: /preamble
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    # the path of the template to render
    template: "components/video.html.twig"

    # the response status code (default: 200)
    statusCode: 200

    # special options defined by Symfony to set the page cache
    maxAge: 86400
    sharedAge: 86400

    # whether or not caching should apply for client caches only
    private: true

legal:
  path: /legal
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    # the path of the template to render
    template: "components/legal.html.twig"

    # the response status code (default: 200)
    statusCode: 200

    # special options defined by Symfony to set the page cache
    maxAge: 86400
    sharedAge: 86400

    # whether or not caching should apply for client caches only
    private: true
